name: Publish toolkit

on:
  release:
    types: [published]

env:
  OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
  OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
  GPG_PRIVATE_KEY: ${{ secrets.PGP_SECRET }}
  PGP_PASSWORD: ${{ secrets.PGP_PASSPHRASE }}

jobs:
  publish:
    name: Release toolkit and publish
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: coursier/cache-action@v6.3

      - name: Setup Scala CLI
        uses: VirtusLab/scala-cli-setup@main

      - name: Publish Toolkit locally for JVM
        run: scala-cli --power publish local --cross Toolkit.scala publish-conf.scala 
      
      - name: Publish Toolkit locally for native
        run: scala-cli --power publish local --cross --native Toolkit.scala publish-conf.scala 

      - name: Publish Toolkit locally for JS
        run: scala-cli --power publish local --cross --js Toolkit.scala publish-conf.scala 

      - name: Publish Toolkit for JVM
        run: scala-cli --power publish --cross Toolkit.scala publish-conf.scala 

      - name: Publish Toolkit for native
        run: scala-cli --power publish --cross --native Toolkit.scala publish-conf.scala 

      - name: Publish Toolkit for JS
        run: scala-cli --power publish --cross --js Toolkit.scala publish-conf.scala 
        continue-on-error: true

      - name: Publish Toolkit Test for JVM
        run: scala-cli --power publish --toolkit $TOOLKIT_VERSION --cross ToolkitTest.scala publish-conf.scala 
        continue-on-error: true
        env:
          TOOLKIT_VERSION: ${{ github.ref_name }}

      - name: Publish Toolkit Test for native
        run: scala-cli --power publish --native --toolkit $TOOLKIT_VERSION --cross ToolkitTest.scala publish-conf.scala 
        continue-on-error: true
        env:
          TOOLKIT_VERSION: ${{ github.ref_name }}

      - name: Publish Toolkit Test for JS
        run: scala-cli --power publish --js --toolkit $TOOLKIT_VERSION --cross ToolkitTest.scala publish-conf.scala 
        continue-on-error: true
        env:
          TOOLKIT_VERSION: ${{ github.ref_name }}
